//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace CDMOLNET_Final.ServiceCD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCD.CDServiceSoap")]
    public interface CDServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.HelloWorldResponse> HelloWorldAsync(CDMOLNET_Final.ServiceCD.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/finnsUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.finnsUserResponse> finnsUserAsync(CDMOLNET_Final.ServiceCD.finnsUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.addUserResponse> addUserAsync(CDMOLNET_Final.ServiceCD.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loggaIn", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.loggaInResponse> loggaInAsync(CDMOLNET_Final.ServiceCD.loggaInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getArtist10", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getArtist10Response> getArtist10Async(CDMOLNET_Final.ServiceCD.getArtist10Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlbum10", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getAlbum10Response> getAlbum10Async(CDMOLNET_Final.ServiceCD.getAlbum10Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getArtistResponse> getArtistAsync(CDMOLNET_Final.ServiceCD.getArtistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/senasteInnlagda", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.senasteInnlagdaResponse> senasteInnlagdaAsync(CDMOLNET_Final.ServiceCD.senasteInnlagdaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/minStat", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.minStatResponse> minStatAsync(CDMOLNET_Final.ServiceCD.minStatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AntalperAr", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.AntalperArResponse> AntalperArAsync(CDMOLNET_Final.ServiceCD.AntalperArRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/media", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.mediaResponse> mediaAsync(CDMOLNET_Final.ServiceCD.mediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlbum", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getAlbumResponse> getAlbumAsync(CDMOLNET_Final.ServiceCD.getAlbumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTracks", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getTracksResponse> getTracksAsync(CDMOLNET_Final.ServiceCD.getTracksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/artistInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.artistInfoResponse> artistInfoAsync(CDMOLNET_Final.ServiceCD.artistInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/topAlbum", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.topAlbumResponse> topAlbumAsync(CDMOLNET_Final.ServiceCD.topAlbumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/artistLiknande", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.artistLiknandeResponse> artistLiknandeAsync(CDMOLNET_Final.ServiceCD.artistLiknandeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTracksByArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getTracksByArtistResponse> getTracksByArtistAsync(CDMOLNET_Final.ServiceCD.getTracksByArtistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArtistInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.ArtistInfoResponse1> ArtistInfo1Async(CDMOLNET_Final.ServiceCD.ArtistInfoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LiknandeArtister", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.LiknandeArtisterResponse> LiknandeArtisterAsync(CDMOLNET_Final.ServiceCD.LiknandeArtisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShortAristInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.ShortAristInfoResponse> ShortAristInfoAsync(CDMOLNET_Final.ServiceCD.ShortAristInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArtistAlbum", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.GetArtistAlbumResponse> GetArtistAlbumAsync(CDMOLNET_Final.ServiceCD.GetArtistAlbumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlbumTracks", ReplyAction="*")]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.AlbumTracksResponse> AlbumTracksAsync(CDMOLNET_Final.ServiceCD.AlbumTracksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CDMOLNET_Final.ServiceCD.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CDMOLNET_Final.ServiceCD.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class finnsUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="finnsUser", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.finnsUserRequestBody Body;
        
        public finnsUserRequest() {
        }
        
        public finnsUserRequest(CDMOLNET_Final.ServiceCD.finnsUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class finnsUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNamn;
        
        public finnsUserRequestBody() {
        }
        
        public finnsUserRequestBody(string userNamn) {
            this.userNamn = userNamn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class finnsUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="finnsUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.finnsUserResponseBody Body;
        
        public finnsUserResponse() {
        }
        
        public finnsUserResponse(CDMOLNET_Final.ServiceCD.finnsUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class finnsUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string finnsUserResult;
        
        public finnsUserResponseBody() {
        }
        
        public finnsUserResponseBody(string finnsUserResult) {
            this.finnsUserResult = finnsUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(CDMOLNET_Final.ServiceCD.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fnamn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string enamn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string epost;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usernamn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(string fnamn, string enamn, string epost, string usernamn, string password) {
            this.fnamn = fnamn;
            this.enamn = enamn;
            this.epost = epost;
            this.usernamn = usernamn;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(CDMOLNET_Final.ServiceCD.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addUserResult;
        
        public addUserResponseBody() {
        }
        
        public addUserResponseBody(string addUserResult) {
            this.addUserResult = addUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggaInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loggaIn", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.loggaInRequestBody Body;
        
        public loggaInRequest() {
        }
        
        public loggaInRequest(CDMOLNET_Final.ServiceCD.loggaInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loggaInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usernamn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loggaInRequestBody() {
        }
        
        public loggaInRequestBody(string usernamn, string password) {
            this.usernamn = usernamn;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggaInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loggaInResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.loggaInResponseBody Body;
        
        public loggaInResponse() {
        }
        
        public loggaInResponse(CDMOLNET_Final.ServiceCD.loggaInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loggaInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loggaInResult;
        
        public loggaInResponseBody() {
        }
        
        public loggaInResponseBody(string loggaInResult) {
            this.loggaInResult = loggaInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtist10Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtist10", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getArtist10RequestBody Body;
        
        public getArtist10Request() {
        }
        
        public getArtist10Request(CDMOLNET_Final.ServiceCD.getArtist10RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getArtist10RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        public getArtist10RequestBody() {
        }
        
        public getArtist10RequestBody(string userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtist10Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtist10Response", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getArtist10ResponseBody Body;
        
        public getArtist10Response() {
        }
        
        public getArtist10Response(CDMOLNET_Final.ServiceCD.getArtist10ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getArtist10ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getArtist10Result;
        
        public getArtist10ResponseBody() {
        }
        
        public getArtist10ResponseBody(string getArtist10Result) {
            this.getArtist10Result = getArtist10Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAlbum10Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAlbum10", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getAlbum10RequestBody Body;
        
        public getAlbum10Request() {
        }
        
        public getAlbum10Request(CDMOLNET_Final.ServiceCD.getAlbum10RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAlbum10RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Artist;
        
        public getAlbum10RequestBody() {
        }
        
        public getAlbum10RequestBody(string userID, string Artist) {
            this.userID = userID;
            this.Artist = Artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAlbum10Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAlbum10Response", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getAlbum10ResponseBody Body;
        
        public getAlbum10Response() {
        }
        
        public getAlbum10Response(CDMOLNET_Final.ServiceCD.getAlbum10ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAlbum10ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAlbum10Result;
        
        public getAlbum10ResponseBody() {
        }
        
        public getAlbum10ResponseBody(string getAlbum10Result) {
            this.getAlbum10Result = getAlbum10Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtist", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getArtistRequestBody Body;
        
        public getArtistRequest() {
        }
        
        public getArtistRequest(CDMOLNET_Final.ServiceCD.getArtistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getArtistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        public getArtistRequestBody() {
        }
        
        public getArtistRequestBody(string userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getArtistResponseBody Body;
        
        public getArtistResponse() {
        }
        
        public getArtistResponse(CDMOLNET_Final.ServiceCD.getArtistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getArtistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getArtistResult;
        
        public getArtistResponseBody() {
        }
        
        public getArtistResponseBody(object getArtistResult) {
            this.getArtistResult = getArtistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class senasteInnlagdaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="senasteInnlagda", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.senasteInnlagdaRequestBody Body;
        
        public senasteInnlagdaRequest() {
        }
        
        public senasteInnlagdaRequest(CDMOLNET_Final.ServiceCD.senasteInnlagdaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class senasteInnlagdaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public senasteInnlagdaRequestBody() {
        }
        
        public senasteInnlagdaRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class senasteInnlagdaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="senasteInnlagdaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.senasteInnlagdaResponseBody Body;
        
        public senasteInnlagdaResponse() {
        }
        
        public senasteInnlagdaResponse(CDMOLNET_Final.ServiceCD.senasteInnlagdaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class senasteInnlagdaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object senasteInnlagdaResult;
        
        public senasteInnlagdaResponseBody() {
        }
        
        public senasteInnlagdaResponseBody(object senasteInnlagdaResult) {
            this.senasteInnlagdaResult = senasteInnlagdaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class minStatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="minStat", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.minStatRequestBody Body;
        
        public minStatRequest() {
        }
        
        public minStatRequest(CDMOLNET_Final.ServiceCD.minStatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class minStatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public minStatRequestBody() {
        }
        
        public minStatRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class minStatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="minStatResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.minStatResponseBody Body;
        
        public minStatResponse() {
        }
        
        public minStatResponse(CDMOLNET_Final.ServiceCD.minStatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class minStatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string minStatResult;
        
        public minStatResponseBody() {
        }
        
        public minStatResponseBody(string minStatResult) {
            this.minStatResult = minStatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AntalperArRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AntalperAr", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.AntalperArRequestBody Body;
        
        public AntalperArRequest() {
        }
        
        public AntalperArRequest(CDMOLNET_Final.ServiceCD.AntalperArRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AntalperArRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public AntalperArRequestBody() {
        }
        
        public AntalperArRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AntalperArResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AntalperArResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.AntalperArResponseBody Body;
        
        public AntalperArResponse() {
        }
        
        public AntalperArResponse(CDMOLNET_Final.ServiceCD.AntalperArResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AntalperArResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AntalperArResult;
        
        public AntalperArResponseBody() {
        }
        
        public AntalperArResponseBody(string AntalperArResult) {
            this.AntalperArResult = AntalperArResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="media", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.mediaRequestBody Body;
        
        public mediaRequest() {
        }
        
        public mediaRequest(CDMOLNET_Final.ServiceCD.mediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public mediaRequestBody() {
        }
        
        public mediaRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.mediaResponseBody Body;
        
        public mediaResponse() {
        }
        
        public mediaResponse(CDMOLNET_Final.ServiceCD.mediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mediaResult;
        
        public mediaResponseBody() {
        }
        
        public mediaResponseBody(string mediaResult) {
            this.mediaResult = mediaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAlbumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAlbum", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getAlbumRequestBody Body;
        
        public getAlbumRequest() {
        }
        
        public getAlbumRequest(CDMOLNET_Final.ServiceCD.getAlbumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAlbumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Artist;
        
        public getAlbumRequestBody() {
        }
        
        public getAlbumRequestBody(string userID, string Artist) {
            this.userID = userID;
            this.Artist = Artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAlbumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAlbumResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getAlbumResponseBody Body;
        
        public getAlbumResponse() {
        }
        
        public getAlbumResponse(CDMOLNET_Final.ServiceCD.getAlbumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAlbumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getAlbumResult;
        
        public getAlbumResponseBody() {
        }
        
        public getAlbumResponseBody(object getAlbumResult) {
            this.getAlbumResult = getAlbumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTracksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTracks", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getTracksRequestBody Body;
        
        public getTracksRequest() {
        }
        
        public getTracksRequest(CDMOLNET_Final.ServiceCD.getTracksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTracksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DiscID;
        
        public getTracksRequestBody() {
        }
        
        public getTracksRequestBody(string userID, string DiscID) {
            this.userID = userID;
            this.DiscID = DiscID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTracksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTracksResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getTracksResponseBody Body;
        
        public getTracksResponse() {
        }
        
        public getTracksResponse(CDMOLNET_Final.ServiceCD.getTracksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTracksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getTracksResult;
        
        public getTracksResponseBody() {
        }
        
        public getTracksResponseBody(object getTracksResult) {
            this.getTracksResult = getTracksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class artistInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="artistInfo", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.artistInfoRequestBody Body;
        
        public artistInfoRequest() {
        }
        
        public artistInfoRequest(CDMOLNET_Final.ServiceCD.artistInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class artistInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        public artistInfoRequestBody() {
        }
        
        public artistInfoRequestBody(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class artistInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="artistInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.artistInfoResponseBody Body;
        
        public artistInfoResponse() {
        }
        
        public artistInfoResponse(CDMOLNET_Final.ServiceCD.artistInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class artistInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artistInfoResult;
        
        public artistInfoResponseBody() {
        }
        
        public artistInfoResponseBody(string artistInfoResult) {
            this.artistInfoResult = artistInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class topAlbumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="topAlbum", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.topAlbumRequestBody Body;
        
        public topAlbumRequest() {
        }
        
        public topAlbumRequest(CDMOLNET_Final.ServiceCD.topAlbumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class topAlbumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        public topAlbumRequestBody() {
        }
        
        public topAlbumRequestBody(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class topAlbumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="topAlbumResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.topAlbumResponseBody Body;
        
        public topAlbumResponse() {
        }
        
        public topAlbumResponse(CDMOLNET_Final.ServiceCD.topAlbumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class topAlbumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string topAlbumResult;
        
        public topAlbumResponseBody() {
        }
        
        public topAlbumResponseBody(string topAlbumResult) {
            this.topAlbumResult = topAlbumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class artistLiknandeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="artistLiknande", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.artistLiknandeRequestBody Body;
        
        public artistLiknandeRequest() {
        }
        
        public artistLiknandeRequest(CDMOLNET_Final.ServiceCD.artistLiknandeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class artistLiknandeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        public artistLiknandeRequestBody() {
        }
        
        public artistLiknandeRequestBody(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class artistLiknandeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="artistLiknandeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.artistLiknandeResponseBody Body;
        
        public artistLiknandeResponse() {
        }
        
        public artistLiknandeResponse(CDMOLNET_Final.ServiceCD.artistLiknandeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class artistLiknandeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artistLiknandeResult;
        
        public artistLiknandeResponseBody() {
        }
        
        public artistLiknandeResponseBody(string artistLiknandeResult) {
            this.artistLiknandeResult = artistLiknandeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTracksByArtistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTracksByArtist", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getTracksByArtistRequestBody Body;
        
        public getTracksByArtistRequest() {
        }
        
        public getTracksByArtistRequest(CDMOLNET_Final.ServiceCD.getTracksByArtistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTracksByArtistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Artist;
        
        public getTracksByArtistRequestBody() {
        }
        
        public getTracksByArtistRequestBody(string userID, string Artist) {
            this.userID = userID;
            this.Artist = Artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTracksByArtistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTracksByArtistResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.getTracksByArtistResponseBody Body;
        
        public getTracksByArtistResponse() {
        }
        
        public getTracksByArtistResponse(CDMOLNET_Final.ServiceCD.getTracksByArtistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTracksByArtistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getTracksByArtistResult;
        
        public getTracksByArtistResponseBody() {
        }
        
        public getTracksByArtistResponseBody(object getTracksByArtistResult) {
            this.getTracksByArtistResult = getTracksByArtistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ArtistInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ArtistInfoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string artist;
        
        public ArtistInfoRequest1() {
        }
        
        public ArtistInfoRequest1(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ArtistInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ArtistInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object ArtistInfoResult;
        
        public ArtistInfoResponse1() {
        }
        
        public ArtistInfoResponse1(object ArtistInfoResult) {
            this.ArtistInfoResult = ArtistInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LiknandeArtisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LiknandeArtister", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.LiknandeArtisterRequestBody Body;
        
        public LiknandeArtisterRequest() {
        }
        
        public LiknandeArtisterRequest(CDMOLNET_Final.ServiceCD.LiknandeArtisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LiknandeArtisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        public LiknandeArtisterRequestBody() {
        }
        
        public LiknandeArtisterRequestBody(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LiknandeArtisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LiknandeArtisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.LiknandeArtisterResponseBody Body;
        
        public LiknandeArtisterResponse() {
        }
        
        public LiknandeArtisterResponse(CDMOLNET_Final.ServiceCD.LiknandeArtisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LiknandeArtisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object LiknandeArtisterResult;
        
        public LiknandeArtisterResponseBody() {
        }
        
        public LiknandeArtisterResponseBody(object LiknandeArtisterResult) {
            this.LiknandeArtisterResult = LiknandeArtisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShortAristInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShortAristInfo", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.ShortAristInfoRequestBody Body;
        
        public ShortAristInfoRequest() {
        }
        
        public ShortAristInfoRequest(CDMOLNET_Final.ServiceCD.ShortAristInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShortAristInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string artist;
        
        public ShortAristInfoRequestBody() {
        }
        
        public ShortAristInfoRequestBody(string artist) {
            this.artist = artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShortAristInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShortAristInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.ShortAristInfoResponseBody Body;
        
        public ShortAristInfoResponse() {
        }
        
        public ShortAristInfoResponse(CDMOLNET_Final.ServiceCD.ShortAristInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShortAristInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object ShortAristInfoResult;
        
        public ShortAristInfoResponseBody() {
        }
        
        public ShortAristInfoResponseBody(object ShortAristInfoResult) {
            this.ShortAristInfoResult = ShortAristInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArtistAlbumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArtistAlbum", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.GetArtistAlbumRequestBody Body;
        
        public GetArtistAlbumRequest() {
        }
        
        public GetArtistAlbumRequest(CDMOLNET_Final.ServiceCD.GetArtistAlbumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArtistAlbumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Artist;
        
        public GetArtistAlbumRequestBody() {
        }
        
        public GetArtistAlbumRequestBody(string Artist) {
            this.Artist = Artist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArtistAlbumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArtistAlbumResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.GetArtistAlbumResponseBody Body;
        
        public GetArtistAlbumResponse() {
        }
        
        public GetArtistAlbumResponse(CDMOLNET_Final.ServiceCD.GetArtistAlbumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArtistAlbumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetArtistAlbumResult;
        
        public GetArtistAlbumResponseBody() {
        }
        
        public GetArtistAlbumResponseBody(string GetArtistAlbumResult) {
            this.GetArtistAlbumResult = GetArtistAlbumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlbumTracksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlbumTracks", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.AlbumTracksRequestBody Body;
        
        public AlbumTracksRequest() {
        }
        
        public AlbumTracksRequest(CDMOLNET_Final.ServiceCD.AlbumTracksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlbumTracksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Artist;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Album;
        
        public AlbumTracksRequestBody() {
        }
        
        public AlbumTracksRequestBody(string Artist, string Album) {
            this.Artist = Artist;
            this.Album = Album;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlbumTracksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlbumTracksResponse", Namespace="http://tempuri.org/", Order=0)]
        public CDMOLNET_Final.ServiceCD.AlbumTracksResponseBody Body;
        
        public AlbumTracksResponse() {
        }
        
        public AlbumTracksResponse(CDMOLNET_Final.ServiceCD.AlbumTracksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlbumTracksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AlbumTracksResult;
        
        public AlbumTracksResponseBody() {
        }
        
        public AlbumTracksResponseBody(string AlbumTracksResult) {
            this.AlbumTracksResult = AlbumTracksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CDServiceSoapChannel : CDMOLNET_Final.ServiceCD.CDServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDServiceSoapClient : System.ServiceModel.ClientBase<CDMOLNET_Final.ServiceCD.CDServiceSoap>, CDMOLNET_Final.ServiceCD.CDServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CDServiceSoapClient() : 
                base(CDServiceSoapClient.GetDefaultBinding(), CDServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.CDServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CDServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CDServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CDServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CDServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CDServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CDServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CDServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CDServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.HelloWorldResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.HelloWorldAsync(CDMOLNET_Final.ServiceCD.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.HelloWorldResponse> HelloWorldAsync() {
            CDMOLNET_Final.ServiceCD.HelloWorldRequest inValue = new CDMOLNET_Final.ServiceCD.HelloWorldRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.HelloWorldRequestBody();
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.finnsUserResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.finnsUserAsync(CDMOLNET_Final.ServiceCD.finnsUserRequest request) {
            return base.Channel.finnsUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.finnsUserResponse> finnsUserAsync(string userNamn) {
            CDMOLNET_Final.ServiceCD.finnsUserRequest inValue = new CDMOLNET_Final.ServiceCD.finnsUserRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.finnsUserRequestBody();
            inValue.Body.userNamn = userNamn;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).finnsUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.addUserResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.addUserAsync(CDMOLNET_Final.ServiceCD.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.addUserResponse> addUserAsync(string fnamn, string enamn, string epost, string usernamn, string password) {
            CDMOLNET_Final.ServiceCD.addUserRequest inValue = new CDMOLNET_Final.ServiceCD.addUserRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.addUserRequestBody();
            inValue.Body.fnamn = fnamn;
            inValue.Body.enamn = enamn;
            inValue.Body.epost = epost;
            inValue.Body.usernamn = usernamn;
            inValue.Body.password = password;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.loggaInResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.loggaInAsync(CDMOLNET_Final.ServiceCD.loggaInRequest request) {
            return base.Channel.loggaInAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.loggaInResponse> loggaInAsync(string usernamn, string password) {
            CDMOLNET_Final.ServiceCD.loggaInRequest inValue = new CDMOLNET_Final.ServiceCD.loggaInRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.loggaInRequestBody();
            inValue.Body.usernamn = usernamn;
            inValue.Body.password = password;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).loggaInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getArtist10Response> CDMOLNET_Final.ServiceCD.CDServiceSoap.getArtist10Async(CDMOLNET_Final.ServiceCD.getArtist10Request request) {
            return base.Channel.getArtist10Async(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getArtist10Response> getArtist10Async(string userID) {
            CDMOLNET_Final.ServiceCD.getArtist10Request inValue = new CDMOLNET_Final.ServiceCD.getArtist10Request();
            inValue.Body = new CDMOLNET_Final.ServiceCD.getArtist10RequestBody();
            inValue.Body.userID = userID;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).getArtist10Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getAlbum10Response> CDMOLNET_Final.ServiceCD.CDServiceSoap.getAlbum10Async(CDMOLNET_Final.ServiceCD.getAlbum10Request request) {
            return base.Channel.getAlbum10Async(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getAlbum10Response> getAlbum10Async(string userID, string Artist) {
            CDMOLNET_Final.ServiceCD.getAlbum10Request inValue = new CDMOLNET_Final.ServiceCD.getAlbum10Request();
            inValue.Body = new CDMOLNET_Final.ServiceCD.getAlbum10RequestBody();
            inValue.Body.userID = userID;
            inValue.Body.Artist = Artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).getAlbum10Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getArtistResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.getArtistAsync(CDMOLNET_Final.ServiceCD.getArtistRequest request) {
            return base.Channel.getArtistAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getArtistResponse> getArtistAsync(string userID) {
            CDMOLNET_Final.ServiceCD.getArtistRequest inValue = new CDMOLNET_Final.ServiceCD.getArtistRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.getArtistRequestBody();
            inValue.Body.userID = userID;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).getArtistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.senasteInnlagdaResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.senasteInnlagdaAsync(CDMOLNET_Final.ServiceCD.senasteInnlagdaRequest request) {
            return base.Channel.senasteInnlagdaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.senasteInnlagdaResponse> senasteInnlagdaAsync(int userId) {
            CDMOLNET_Final.ServiceCD.senasteInnlagdaRequest inValue = new CDMOLNET_Final.ServiceCD.senasteInnlagdaRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.senasteInnlagdaRequestBody();
            inValue.Body.userId = userId;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).senasteInnlagdaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.minStatResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.minStatAsync(CDMOLNET_Final.ServiceCD.minStatRequest request) {
            return base.Channel.minStatAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.minStatResponse> minStatAsync(string userId) {
            CDMOLNET_Final.ServiceCD.minStatRequest inValue = new CDMOLNET_Final.ServiceCD.minStatRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.minStatRequestBody();
            inValue.Body.userId = userId;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).minStatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.AntalperArResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.AntalperArAsync(CDMOLNET_Final.ServiceCD.AntalperArRequest request) {
            return base.Channel.AntalperArAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.AntalperArResponse> AntalperArAsync(string userId) {
            CDMOLNET_Final.ServiceCD.AntalperArRequest inValue = new CDMOLNET_Final.ServiceCD.AntalperArRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.AntalperArRequestBody();
            inValue.Body.userId = userId;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).AntalperArAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.mediaResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.mediaAsync(CDMOLNET_Final.ServiceCD.mediaRequest request) {
            return base.Channel.mediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.mediaResponse> mediaAsync(string userId) {
            CDMOLNET_Final.ServiceCD.mediaRequest inValue = new CDMOLNET_Final.ServiceCD.mediaRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.mediaRequestBody();
            inValue.Body.userId = userId;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).mediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getAlbumResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.getAlbumAsync(CDMOLNET_Final.ServiceCD.getAlbumRequest request) {
            return base.Channel.getAlbumAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getAlbumResponse> getAlbumAsync(string userID, string Artist) {
            CDMOLNET_Final.ServiceCD.getAlbumRequest inValue = new CDMOLNET_Final.ServiceCD.getAlbumRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.getAlbumRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.Artist = Artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).getAlbumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getTracksResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.getTracksAsync(CDMOLNET_Final.ServiceCD.getTracksRequest request) {
            return base.Channel.getTracksAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getTracksResponse> getTracksAsync(string userID, string DiscID) {
            CDMOLNET_Final.ServiceCD.getTracksRequest inValue = new CDMOLNET_Final.ServiceCD.getTracksRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.getTracksRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.DiscID = DiscID;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).getTracksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.artistInfoResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.artistInfoAsync(CDMOLNET_Final.ServiceCD.artistInfoRequest request) {
            return base.Channel.artistInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.artistInfoResponse> artistInfoAsync(string artist) {
            CDMOLNET_Final.ServiceCD.artistInfoRequest inValue = new CDMOLNET_Final.ServiceCD.artistInfoRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.artistInfoRequestBody();
            inValue.Body.artist = artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).artistInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.topAlbumResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.topAlbumAsync(CDMOLNET_Final.ServiceCD.topAlbumRequest request) {
            return base.Channel.topAlbumAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.topAlbumResponse> topAlbumAsync(string artist) {
            CDMOLNET_Final.ServiceCD.topAlbumRequest inValue = new CDMOLNET_Final.ServiceCD.topAlbumRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.topAlbumRequestBody();
            inValue.Body.artist = artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).topAlbumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.artistLiknandeResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.artistLiknandeAsync(CDMOLNET_Final.ServiceCD.artistLiknandeRequest request) {
            return base.Channel.artistLiknandeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.artistLiknandeResponse> artistLiknandeAsync(string artist) {
            CDMOLNET_Final.ServiceCD.artistLiknandeRequest inValue = new CDMOLNET_Final.ServiceCD.artistLiknandeRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.artistLiknandeRequestBody();
            inValue.Body.artist = artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).artistLiknandeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getTracksByArtistResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.getTracksByArtistAsync(CDMOLNET_Final.ServiceCD.getTracksByArtistRequest request) {
            return base.Channel.getTracksByArtistAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.getTracksByArtistResponse> getTracksByArtistAsync(string userID, string Artist) {
            CDMOLNET_Final.ServiceCD.getTracksByArtistRequest inValue = new CDMOLNET_Final.ServiceCD.getTracksByArtistRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.getTracksByArtistRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.Artist = Artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).getTracksByArtistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.ArtistInfoResponse1> CDMOLNET_Final.ServiceCD.CDServiceSoap.ArtistInfo1Async(CDMOLNET_Final.ServiceCD.ArtistInfoRequest1 request) {
            return base.Channel.ArtistInfo1Async(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.ArtistInfoResponse1> ArtistInfo1Async(string artist) {
            CDMOLNET_Final.ServiceCD.ArtistInfoRequest1 inValue = new CDMOLNET_Final.ServiceCD.ArtistInfoRequest1();
            inValue.artist = artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).ArtistInfo1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.LiknandeArtisterResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.LiknandeArtisterAsync(CDMOLNET_Final.ServiceCD.LiknandeArtisterRequest request) {
            return base.Channel.LiknandeArtisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.LiknandeArtisterResponse> LiknandeArtisterAsync(string artist) {
            CDMOLNET_Final.ServiceCD.LiknandeArtisterRequest inValue = new CDMOLNET_Final.ServiceCD.LiknandeArtisterRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.LiknandeArtisterRequestBody();
            inValue.Body.artist = artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).LiknandeArtisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.ShortAristInfoResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.ShortAristInfoAsync(CDMOLNET_Final.ServiceCD.ShortAristInfoRequest request) {
            return base.Channel.ShortAristInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.ShortAristInfoResponse> ShortAristInfoAsync(string artist) {
            CDMOLNET_Final.ServiceCD.ShortAristInfoRequest inValue = new CDMOLNET_Final.ServiceCD.ShortAristInfoRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.ShortAristInfoRequestBody();
            inValue.Body.artist = artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).ShortAristInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.GetArtistAlbumResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.GetArtistAlbumAsync(CDMOLNET_Final.ServiceCD.GetArtistAlbumRequest request) {
            return base.Channel.GetArtistAlbumAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.GetArtistAlbumResponse> GetArtistAlbumAsync(string Artist) {
            CDMOLNET_Final.ServiceCD.GetArtistAlbumRequest inValue = new CDMOLNET_Final.ServiceCD.GetArtistAlbumRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.GetArtistAlbumRequestBody();
            inValue.Body.Artist = Artist;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).GetArtistAlbumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.AlbumTracksResponse> CDMOLNET_Final.ServiceCD.CDServiceSoap.AlbumTracksAsync(CDMOLNET_Final.ServiceCD.AlbumTracksRequest request) {
            return base.Channel.AlbumTracksAsync(request);
        }
        
        public System.Threading.Tasks.Task<CDMOLNET_Final.ServiceCD.AlbumTracksResponse> AlbumTracksAsync(string Artist, string Album) {
            CDMOLNET_Final.ServiceCD.AlbumTracksRequest inValue = new CDMOLNET_Final.ServiceCD.AlbumTracksRequest();
            inValue.Body = new CDMOLNET_Final.ServiceCD.AlbumTracksRequestBody();
            inValue.Body.Artist = Artist;
            inValue.Body.Album = Album;
            return ((CDMOLNET_Final.ServiceCD.CDServiceSoap)(this)).AlbumTracksAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.CDServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.CDServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://cdmolnet.se/CDService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return CDServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.CDServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return CDServiceSoapClient.GetEndpointAddress(EndpointConfiguration.CDServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            CDServiceSoap,
        }
    }
}
